### ISSUE TITLE
Installation de Node.js si version supérieur à 5

### ISSUE THREAD

**Issue by FabriceGo** [lunarok/jeedom_dashbutton#10]
Bonjour Cedric,

L'installation des dépendances du plugin Dashbutton contrôle si node.js est en version 4 ou 5, si l'on a une version supérieur à la version 5, l'installation force une désinstallation de la version 6 ou 8 par exemple, pour réinstaller la version 5.

**Comment by lunarok** [comment]
normal actuellement
