### ISSUE TITLE
Fonctionnement du plugin avec node.js en version supérieur à la v5

### ISSUE THREAD

**Issue by FabriceGo** [lunarok/jeedom_dashbutton#11]
Bonjour Cedric,

Il semble que ce plugin ne fonctionne plus avec une version 6 ou 8 de node.js. 

Raspbian 8 
Linux jeedom 4.9.39-v7+ #1021 SMP Mon Jul 24 11:32:18 BST 2017 armv7l GNU/Linux [8.0]

Log du demon avec node.js d'installé

module.js:538
throw err;
^
Error: Cannot find module 'node-dash-button'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/www/html/plugins/dashbutton/node/dashbutton.js:1:81)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)

Merci.

**Comment by lunarok** [comment]
pas testé avec la v6 ou v8

**Comment by FabriceGo** [comment]
Cela ne fonctionne pas avec node.js v6 et v8 (sur un Raspbian en Jessy à jour de tout).
Je ne sais pas faire les modifications (je ne suis pas dev). Au cas ou, tu comptes faire une adaptation ou pas ? (peu importe quand, c'est juste pour savoir si cela va être adapté).
PS : Peux tu aller voir mes constats sur le fil de maillisterner STP. Je n'arrive pas à trouver un canal pour échanger avec toi sur ce plugin. Il ne fonctionne plus chez pas mal d'utilisateurs).

**Comment by FabriceGo** [comment]
Cédric, si tu me dit que mes problèmes viennent du fait que je suis sur un Raspberry, cela me convient parfaitement comme réponse (j'ai déjà lu de toi, des explications sur cette plateforme vs Debian). Si c'est le cas, je passe sur i386. Ce que je souhaiterais, c'est simplement une confirmation de ta part.

**Comment by lunarok** [comment]
j'en sais rien je m'en sers pas, mais je regarderais pas son comportement avec nodejs 8 avant généralisation

**Comment by FabriceGo** [comment]
Ok, merci pour cela.
Le problème, c'est que "visiblement" maillisterner ne fonctionne plus avec node.js 4 ou 5. Le service tiens avec v6 ou v8 mais le programme ne fonctionne plus (si tu peux aller voir le fil officiel du plugin). Et en v6 et v8, Dashbutton ne fonctionne pas.
Quel est l'emplacement ou il est possible de discuter avec toi de maillistener ?

**Comment by lunarok** [comment]
c'est fait https://github.com/lunarok/jeedom_maillistener/commit/3539041faefa20b60ebc3a1a779989cf0b68aa6e

**Comment by FabriceGo** [comment]
Bonsoir Cedric,
J'ai du supprimer le dossier du plugin maillisterner. Puis je l'ai réinstallé en utilisant l'installation forcé depuis le centre de mise à jour. J'ai réinstallé les dépendances de Dashbutton (donc passage en node.js 5) et hop, tout est tombé en marche. J'ai bien vue qu'il y a les modifications que tu as fais ce jour.
Je ne sais pas comment te dire plus merci !
- c'est sympa.

Du coup, je vois qu'il y a "Configuration" de présent dans la vue des équipements maillistener.
