### ISSUE TITLE
Erreur installation npm sur SYNOLOGY Debian Chroot

### ISSUE THREAD

**Issue by wikijm** [lunarok/jeedom_dashbutton#5]
Bonjour @lunarok,

Je rencontre des difficultés, lors du processus d'installation des dépendances, à installer npm dans le cadre suivant :
Jeedom : Version 2.4.6
Serveur web : nginx 1.6.2
OS : Linux SYNOLOGYATHOME 3.2.40 #15047 Tue Feb 14 02:38:20 CST 2017 armv7l GNU/Linux (Debian Chroot)
Matériel : SYNOLOGY ds213j

Lors de l'installation, nodejs semble s'installer, mais pas npm.
Voici le log _Dashbutton_dep_ :

Début de l'installation
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
libpcap-dev est déjà la plus récente version disponible.
tcpdump est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 1 non mis à jour.
Version actuelle : v0.10.29
KO, version obsolète à upgrader
Suppression du Nodejs existant et installation du paquet recommandé
Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
Le paquet « npm » n'est pas installé, et ne peut donc être supprimé
Les paquets suivants seront ENLEVÉS :
  nodejs*
0 mis à jour, 0 nouvellement installés, 1 à enlever et 1 non mis à jour.
Après cette opération, 2 678 ko d'espace disque seront libérés.
E: Impossible d'écrire le journal (Est-ce que /dev/pts est monté ?) - posix_openpt (2: Aucun fichier ou dossier de ce type)
(Lecture de la base de données... 38741 fichiers et répertoires déjà installés.)
Suppression de nodejs (0.10.29~dfsg-2) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Utilisation du dépot officiel

## Populating apt-get cache...

+ apt-get update
Ign http://ftp.fr.debian.org jessie InRelease
Atteint http://ftp.fr.debian.org jessie-updates InRelease
Atteint http://security.debian.org jessie/updates InRelease
Atteint http://ftp.fr.debian.org jessie Release.gpg
Atteint http://ftp.fr.debian.org jessie Release
Atteint https://deb.nodesource.com jessie InRelease
Atteint http://ftp.fr.debian.org jessie-updates/main Sources
Atteint http://ftp.fr.debian.org jessie-updates/contrib Sources
Atteint http://ftp.fr.debian.org jessie-updates/non-free Sources
Réception de : 1 http://ftp.fr.debian.org jessie-updates/main armhf Packages/DiffIndex [7 408 B]
Atteint http://ftp.fr.debian.org jessie-updates/contrib armhf Packages
Réception de : 2 http://ftp.fr.debian.org jessie-updates/non-free armhf Packages/DiffIndex [736 B]
Atteint http://ftp.fr.debian.org jessie-updates/contrib Translation-en
Réception de : 3 http://ftp.fr.debian.org jessie-updates/main Translation-en/DiffIndex [2 704 B]
Réception de : 4 http://ftp.fr.debian.org jessie-updates/non-free Translation-en/DiffIndex [736 B]
Atteint http://security.debian.org jessie/updates/main Sources
Atteint http://security.debian.org jessie/updates/contrib Sources
Atteint http://security.debian.org jessie/updates/non-free Sources
Atteint http://security.debian.org jessie/updates/main armhf Packages
Atteint http://security.debian.org jessie/updates/contrib armhf Packages
Atteint http://security.debian.org jessie/updates/non-free armhf Packages
Atteint http://security.debian.org jessie/updates/contrib Translation-en
Atteint http://security.debian.org jessie/updates/main Translation-en
Atteint http://security.debian.org jessie/updates/non-free Translation-en
Atteint http://ftp.fr.debian.org jessie/main Sources
Atteint http://ftp.fr.debian.org jessie/contrib Sources
Atteint http://ftp.fr.debian.org jessie/non-free Sources
Atteint http://ftp.fr.debian.org jessie/main armhf Packages
Atteint http://ftp.fr.debian.org jessie/contrib armhf Packages
Atteint http://ftp.fr.debian.org jessie/non-free armhf Packages
Atteint http://ftp.fr.debian.org jessie/contrib Translation-en
Atteint http://ftp.fr.debian.org jessie/main Translation-fr
Atteint http://ftp.fr.debian.org jessie/main Translation-en
Atteint http://ftp.fr.debian.org jessie/non-free Translation-en
Atteint https://deb.nodesource.com jessie/main Sources
Atteint https://deb.nodesource.com jessie/main armhf Packages
Réception de : 5 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 6 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 7 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 8 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 9 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 10 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 11 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 12 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 13 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 14 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 15 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 16 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 17 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Ign https://deb.nodesource.com jessie/main Translation-fr_FR
Réception de : 18 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Ign https://deb.nodesource.com jessie/main Translation-fr
Réception de : 19 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
11,6 ko réceptionnés en 52s (221 o/s)
Lecture des listes de paquets…

## Confirming "jessie" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_5.x/dists/jessie/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v5.x repo...

+ echo 'deb https://deb.nodesource.com/node_5.x jessie main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_5.x jessie main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Ign http://ftp.fr.debian.org jessie InRelease
Atteint http://ftp.fr.debian.org jessie-updates InRelease
Atteint http://security.debian.org jessie/updates InRelease
Atteint http://ftp.fr.debian.org jessie Release.gpg
Atteint http://ftp.fr.debian.org jessie Release
Atteint https://deb.nodesource.com jessie InRelease
Atteint http://ftp.fr.debian.org jessie-updates/main Sources
Atteint http://ftp.fr.debian.org jessie-updates/contrib Sources
Atteint http://ftp.fr.debian.org jessie-updates/non-free Sources
Réception de : 1 http://ftp.fr.debian.org jessie-updates/main armhf Packages/DiffIndex [7 408 B]
Atteint http://ftp.fr.debian.org jessie-updates/contrib armhf Packages
Réception de : 2 http://ftp.fr.debian.org jessie-updates/non-free armhf Packages/DiffIndex [736 B]
Atteint http://ftp.fr.debian.org jessie-updates/contrib Translation-en
Réception de : 3 http://ftp.fr.debian.org jessie-updates/main Translation-en/DiffIndex [2 704 B]
Réception de : 4 http://ftp.fr.debian.org jessie-updates/non-free Translation-en/DiffIndex [736 B]
Atteint http://security.debian.org jessie/updates/main Sources
Atteint http://security.debian.org jessie/updates/contrib Sources
Atteint http://security.debian.org jessie/updates/non-free Sources
Atteint http://security.debian.org jessie/updates/main armhf Packages
Atteint http://security.debian.org jessie/updates/contrib armhf Packages
Atteint http://security.debian.org jessie/updates/non-free armhf Packages
Atteint http://security.debian.org jessie/updates/contrib Translation-en
Atteint http://security.debian.org jessie/updates/main Translation-en
Atteint http://security.debian.org jessie/updates/non-free Translation-en
Atteint http://ftp.fr.debian.org jessie/main Sources
Atteint http://ftp.fr.debian.org jessie/contrib Sources
Atteint http://ftp.fr.debian.org jessie/non-free Sources
Atteint http://ftp.fr.debian.org jessie/main armhf Packages
Atteint http://ftp.fr.debian.org jessie/contrib armhf Packages
Atteint http://ftp.fr.debian.org jessie/non-free armhf Packages
Atteint http://ftp.fr.debian.org jessie/contrib Translation-en
Atteint http://ftp.fr.debian.org jessie/main Translation-fr
Atteint http://ftp.fr.debian.org jessie/main Translation-en
Atteint http://ftp.fr.debian.org jessie/non-free Translation-en
Atteint https://deb.nodesource.com jessie/main Sources
Atteint https://deb.nodesource.com jessie/main armhf Packages
Réception de : 5 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 6 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 7 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 8 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 9 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 10 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 11 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 12 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 13 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 14 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Réception de : 15 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Réception de : 16 https://deb.nodesource.com jessie/main Translation-en [162 B]
Réception de : 17 https://deb.nodesource.com jessie/main Translation-fr_FR [162 B]
Ign https://deb.nodesource.com jessie/main Translation-fr_FR
Réception de : 18 https://deb.nodesource.com jessie/main Translation-fr [162 B]
Ign https://deb.nodesource.com jessie/main Translation-fr
Réception de : 19 https://deb.nodesource.com jessie/main Translation-en [162 B]
Ign https://deb.nodesource.com jessie/main Translation-en
11,6 ko réceptionnés en 47s (241 o/s)
Lecture des listes de paquets…

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js v5.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_4.x — Node.js v4 LTS "Argon" (recommended)
   * https://deb.nodesource.com/setup_6.x — Node.js v6 Current

  Please see https://github.com/nodejs/LTS/ for details about which version
  may be appropriate for you.

  The NodeSource Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to use the install scripts.
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 10 seconds ...

## Run `apt-get install nodejs` (as root) to install Node.js v5.x and npm

Lecture des listes de paquets…
Construction de l'arbre des dépendances…
Lecture des informations d'état…
Les NOUVEAUX paquets suivants seront installés :
  nodejs
debconf: Impossible d'initialiser l'interface : Dialog
debconf: (L'interface dialog ne fonctionnera pas avec un terminal rustique (« dumb »), un tampon shell d'Emacs ou sans terminal de contrôle.)
debconf: Utilisation de l'interface Readline en remplacement
debconf: Impossible d'initialiser l'interface : Readline
debconf: (Cette interface a besoin d'un terminal de contrôle.)
debconf: Utilisation de l'interface Teletype en remplacement
dpkg-preconfigure: impossible de réouvrir stdin : 
0 mis à jour, 1 nouvellement installés, 0 à enlever et 1 non mis à jour.
Il est nécessaire de prendre 0 o/620 ko dans les archives.
Après cette opération, 2 678 ko d'espace disque supplémentaires seront utilisés.
E: Impossible d'écrire le journal (Est-ce que /dev/pts est monté ?) - posix_openpt (2: Aucun fichier ou dossier de ce type)
Sélection du paquet nodejs précédemment désélectionné.
(Lecture de la base de données... 38647 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../nodejs_0.10.29~dfsg-2_armhf.deb ...
Dépaquetage de nodejs (0.10.29~dfsg-2) ...
Traitement des actions différées (« triggers ») pour man-db (2.7.0.2-5) ...
Paramétrage de nodejs (0.10.29~dfsg-2) ...
update-alternatives: utilisation de « /usr/bin/nodejs » pour fournir « /usr/bin/js » (js) en mode automatique
Version actuelle : v0.10.29
/var/www/html/plugins/dashbutton/resources/nodejs.sh: ligne 61: npm : commande introuvable
sudo: npm: command not found
/var/www/html/plugins/dashbutton/resources/nodejs.sh: ligne 66: npm : commande introuvable
sudo: npm: command not found

**Comment by wikijm** [comment]
Pour information, la commande `apt install npm` me donne le résultat suivant :

> ash-4.3# apt install npm
> Lecture des listes de paquets... Fait
> Construction de l'arbre des dépendances
> Lecture des informations d'état... Fait
> Les paquets supplémentaires suivants seront installés :
>   libc-ares-dev libjs-underscore libv8-3.14-dev node-abbrev node-ansi
>   node-ansi-color-table node-archy node-async node-block-stream
>   node-combined-stream node-cookie-jar node-delayed-stream node-forever-agent
>   node-form-data node-fstream node-fstream-ignore node-github-url-from-git
>   node-glob node-graceful-fs node-gyp node-inherits node-ini
>   node-json-stringify-safe node-lockfile node-lru-cache node-mime
>   node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt
>   node-normalize-package-data node-npmlog node-once node-osenv node-qs
>   node-read node-read-package-json node-request node-retry node-rimraf
>   node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent
>   node-underscore node-which nodejs-dev
> Paquets suggérés :
>   node-hawk node-aws-sign node-oauth-sign node-http-signature
> Les NOUVEAUX paquets suivants seront installés :
>   libc-ares-dev libv8-3.14-dev node-abbrev node-ansi node-ansi-color-table
>   node-archy node-async node-block-stream node-combined-stream node-cookie-jar
>   node-delayed-stream node-forever-agent node-form-data node-fstream
>   node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs
>   node-gyp node-inherits node-ini node-json-stringify-safe node-lockfile
>   node-lru-cache node-mime node-minimatch node-mkdirp node-mute-stream
>   node-node-uuid node-nopt node-normalize-package-data node-npmlog node-once
>   node-osenv node-qs node-read node-read-package-json node-request node-retry
>   node-rimraf node-semver node-sha node-sigmund node-slide node-tar
>   node-tunnel-agent node-underscore node-which nodejs-dev npm
> Les paquets suivants seront mis à jour :
>   libjs-underscore
> 1 mis à jour, 50 nouvellement installés, 0 à enlever et 1 non mis à jour.
> 1 partiellement installés ou enlevés.
> Il est nécessaire de prendre 0 o/1 264 ko dans les archives.
> Après cette opération, 5 966 ko d'espace disque supplémentaires seront utilisés.
> Souhaitez-vous continuer ? [O/n]

Les paquets suivants sont donc installés :

> libjs-underscore (1.7.0~dfsg-1)
> libv8-3.14-dev (3.14.5.8-8.1)
> node-async (0.8.0-1)
> node-node-uuid (1.4.0-1)
> node-underscore (1.7.0~dfsg-1)
> libc-ares-dev:armhf (1.10.0-2+deb8u1)
> node-abbrev (1.0.5-2)
> node-ansi (0.3.0-2)
> node-ansi-color-table (1.0.0-1)
> node-archy (0.0.2-1)
> node-inherits (2.0.1-1)
> node-block-stream (0.0.7-1)
> node-delayed-stream (0.0.5-1)
> node-combined-stream (0.0.5-1)
> node-cookie-jar (0.3.1-1)
> node-forever-agent (0.5.1-1)
> node-mime (1.2.11-1)
> node-form-data (0.1.0-1)
> node-rimraf (2.2.8-1)
> node-mkdirp (0.5.0-1)
> node-graceful-fs (3.0.2-1)
> node-fstream (0.1.24-1)
> node-lru-cache (2.3.1-1)
> node-sigmund (1.0.0-1)
> node-minimatch (1.0.0-1)
> node-fstream-ignore (0.0.6-2)
> node-github-url-from-git (1.1.1-1)
> node-once (1.1.1-1)
> node-glob (4.0.5-1)
> nodejs-dev (0.10.29~dfsg-2)
> node-nopt (3.0.1-1)
> node-npmlog (0.0.4-1)
> node-osenv (0.1.0-1)
> node-tunnel-agent (0.3.1-1)
> node-json-stringify-safe (5.0.0-1)
> node-qs (2.2.4-1)
> node-request (2.26.1-1)
> node-semver (2.1.0-2)
> node-tar (0.1.18-1)
> node-which (1.0.5-2)
> node-gyp (0.12.2+ds-1)
> node-ini (1.1.0-1)
> node-lockfile (0.4.1-1)
> node-mute-stream (0.0.4-1)
> node-normalize-package-data (0.2.2-1)
> node-read (1.0.5-1)
> node-read-package-json (1.2.4-1)
> node-retry (0.6.0-1)
> node-sha (1.2.3-1)
> node-slide (1.1.4-1)
> npm (1.4.21+ds-2)

**Comment by lunarok** [comment]
Désolé, mais pas de support sur les synology. Ca n'a rien à voir avec le plugin mais la platefirme (armv7)
